### ISSUE TITLE
Problems with collision 

### ISSUE THREAD

**Issue by mallok-s** [stacompsoc/Heap-Project-1#6]
The current collision system doesn't seem to be working properly (like objects seem to be passing through one another)

**Comment by theoden8** [comment]
I assume this happens because if two objects collide in frame 1 and have not left the intersection in frame 2 (which also means they collide), the collision system will change their speeds again, and so they will shake, or just go through. I do not see the fix in this case.

**Comment by theoden8** [comment]
Fixed. Somehow (either, it was me or you) while integrating the vectors into physical object the formula was incorrectly changed.
